// Package symbols — curated stdlib bindings for yaegi. The <pkg>.go files are
// generated by `yaegi extract` (see go:generate below) and fill Symbols in their
// init(). We do NOT import yaegi/stdlib — that would pull the whole stdlib into
// the wasm and defeat the size reduction.
package symbols

import "reflect"

//go:generate go run github.com/traefik/yaegi/cmd/yaegi extract fmt errors strings strconv sort slices maps math math/rand time sync sync/atomic context bufio bytes unicode unicode/utf8

// Symbols is populated by the generated files; passed to i.Use(...).
var Symbols = map[string]map[string]reflect.Value{}
